### ISSUE TITLE
Ruby Not Working

### ISSUE THREAD

**Issue by sergionader** [spatie/ruby-ray#15]
Hello, 

I've followed the Ruby install instructions (https://spatie.be/docs/ray/v1/installation-in-your-project/ruby) and after restarting the ruby server and also restarting Ray, I got the following error when trying something like 
`ray(varName)` 
```#<NoMethodError: undefined method `ray' for #<Api::V1::AdminsController:0x000056054977aae8>
Did you mean?  rand>```

Am i missing anything?
BTW, I have a full Ray license. 

Thanks!

**Comment by AdrianMrn** [comment]
@excid3 @freekmurze  Any idea?

**Comment by excid3** [comment]
I just added ruby-ray to a new app and it's working just fine. Do you have any more details @sergionader?

**Comment by excid3** [comment]
Do you happen to have any files named `ray` that are in the load path? The only thing I can think of is the `require 'ray'` in `ruby/ray.rb` would be finding some other file instead.

I can swap that to a `require_relative` so that we guarantee it doesn't match anything else. That should fix that situation if that was the issue.

**Comment by excid3** [comment]
Changed that in 73ab09b. Try using from `main` and see if that does the trick for you.
